INSERT INTO S_DEPT VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO S_DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO S_DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO S_DEPT VALUES (40,'OPERATIONS','BOSTON');